# Generated by Django 3.0.7 on 2020-09-03 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import penguinbook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_picture', models.ImageField(null=True, upload_to=penguinbook.models.display_picture_directory_path)),
                ('display_cover', models.ImageField(null=True, upload_to=penguinbook.models.display_cover_directory_path)),
                ('display_quotes', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_update_date', models.TimeField(auto_now=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('C', 'Custom')], default='M', max_length=10)),
                ('secondary_school_name', models.CharField(max_length=500, null=True)),
                ('secondary_school_passing_year', models.DateField(null=True)),
                ('heigher_secondary_school_name', models.CharField(max_length=500, null=True)),
                ('heigher_secondary_school_passing_year', models.DateField(null=True)),
                ('under_graduate_collage_name', models.CharField(max_length=500, null=True)),
                ('under_graduate_collage_passing_year', models.DateField(null=True)),
                ('post_graduate_collage_name', models.CharField(max_length=500, null=True)),
                ('post_graduate_passing_year', models.DateField(null=True)),
                ('doctor_of_philosophy_collage_name', models.CharField(max_length=500, null=True)),
                ('doctor_of_philosophy_collage_passing_year', models.DateField(null=True)),
                ('previous_job', models.CharField(max_length=500, null=True)),
                ('current_job', models.CharField(max_length=500, null=True)),
                ('native_place', models.CharField(max_length=500, null=True)),
                ('current_living_place', models.CharField(max_length=500, null=True)),
                ('friendship_status', models.CharField(default='Add Friend', max_length=20)),
                ('number_of_friend_request_to_accept', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField(blank=True, max_length=5000)),
                ('post_image', models.ImageField(blank=True, max_length=1000, upload_to=penguinbook.models.post_image_directory_path)),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('likes', models.SmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_receiver_id', models.SmallIntegerField(null=True)),
                ('message', models.TextField(max_length=100000, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_status', models.CharField(max_length=10, null=True)),
                ('like_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('like_gainer_id', models.SmallIntegerField(null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='penguinbook.Post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendship_status', models.SmallIntegerField(default=0)),
                ('friendship_date', models.DateField(auto_now=True)),
                ('friendship_appraoch', models.CharField(max_length=15, null=True)),
                ('user', models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
